/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddRoute: typeof import('./src/components/PlaygroundPage/AddRoute.vue')['default']
    BoxActions: typeof import('./src/components/PlaygroundPage/BoxActions.vue')['default']
    BoxRouteConfig: typeof import('./src/components/PlaygroundPage/BoxRouteConfig.vue')['default']
    BoxRouteItems: typeof import('./src/components/PlaygroundPage/BoxRouteItems.vue')['default']
    BoxRoutes: typeof import('./src/components/PlaygroundPage/BoxRoutes/BoxRoutes.vue')['default']
    BoxRoutesItem: typeof import('./src/components/PlaygroundPage/BoxRoutes/BoxRoutesItem.vue')['default']
    HippieBtnCollapse: typeof import('./src/components/common/HippieBtnCollapse.vue')['default']
    HippieNavPlayground: typeof import('./src/components/PlaygroundPage/HippieNavPlayground.vue')['default']
    ICarbonBranch: typeof import('~icons/carbon/branch')['default']
    ICarbonCube: typeof import('~icons/carbon/cube')['default']
    ICarbonFunctionMath: typeof import('~icons/carbon/function-math')['default']
    ICarbonSettings: typeof import('~icons/carbon/settings')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
